export const ADD_CURRENT_LOCATION = 'ADD_CURRENT_LOCATION';
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const ADD_LOCATIONs = 'ADD_LOCATIONs';
export const SET_TRACKING_NAME = 'SET_TRACKING_NAME';
